services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - dynamodb
    networks:
      - expense-network

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge
